table_name,column_name,data_type
members,id,uuid
members,email,text
members,full_name,text
members,surname,text
members,given_names,text
members,nationality,text
members,date_of_birth,date
members,passport_no,text
members,photo_url,text
members,city,text
members,country,text
members,tier,text
members,balance_aed,numeric
members,referral_code,text
members,referred_by,uuid
members,paid,boolean
members,stripe_session_id,text
members,stripe_customer_id,text
members,profile_complete,boolean
members,created_at,timestamp with time zone
members,updated_at,timestamp with time zone
members,gender,text
members,show_on_leaderboard,boolean
members,access_code,text
members,role,text
members,status,text
members,phone,text
members,phone_country_code,text
members,verified,boolean
profile_meta,member_id,uuid
profile_meta,bio_age,numeric
profile_meta,chrono_age,integer
profile_meta,vo2_max,numeric
profile_meta,body_fat_pct,numeric
profile_meta,visceral_fat,numeric
profile_meta,sleep_logs,jsonb
profile_meta,pr_bench_kg,numeric
profile_meta,pr_squat_kg,numeric
profile_meta,pr_deadlift_kg,numeric
profile_meta,pr_5k_seconds,integer
profile_meta,pr_10k_seconds,integer
profile_meta,pr_21k_seconds,integer
profile_meta,pr_marathon_sec,integer
profile_meta,pr_swim1k_sec,integer
profile_meta,streak_days,integer
profile_meta,streak_best,integer
profile_meta,skills,jsonb
profile_meta,current_weight_kg,numeric
profile_meta,target_weight_kg,numeric
profile_meta,target_weeks,integer
profile_meta,activity_factor,numeric
profile_meta,reliability_score,numeric
profile_meta,meetups_attended,integer
profile_meta,meetups_no_show,integer
profile_meta,updated_at,timestamp with time zone
profile_meta,pr_dates,jsonb
